"""colunas e relacionamentos

Revision ID: bfc60f644b1b
Revises: 1bd6ba4fb165
Create Date: 2022-10-13 17:34:51.425727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc60f644b1b'
down_revision = '1bd6ba4fb165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treinador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qt_insignias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qt_pokemons', sa.Integer(), nullable=True))
        batch_op.drop_column('qtd_insignias')
        batch_op.drop_column('qtd_pokemons')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treinador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_pokemons', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('qtd_insignias', sa.INTEGER(), nullable=True))
        batch_op.drop_column('qt_pokemons')
        batch_op.drop_column('qt_insignias')

    # ### end Alembic commands ###
