"""Adicionando Treinador Pokemon e Relacionamentos

Revision ID: 02a44ada422c
Revises: 20aef04b02c3
Create Date: 2022-10-13 17:19:34.291663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a44ada422c'
down_revision = '20aef04b02c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('lider_ginasio', sa.Boolean(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('qtd_insignias', sa.Integer(), nullable=True),
    sa.Column('qtd_pokemons', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treinador_id'), 'treinador', ['id'], unique=False)
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('forma', sa.Integer(), nullable=True),
    sa.Column('treinador', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['forma'], ['dominio.valor'], ),
    sa.ForeignKeyConstraint(['tipo'], ['dominio.descricao'], ),
    sa.ForeignKeyConstraint(['treinador'], ['treinador.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_treinador_id'), table_name='treinador')
    op.drop_table('treinador')
    # ### end Alembic commands ###
