"""tabelas e relacionamentos

Revision ID: 1bd6ba4fb165
Revises: 02a44ada422c
Create Date: 2022-10-13 17:32:29.213715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd6ba4fb165'
down_revision = '02a44ada422c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
